---
title: "In_class_10_1_reshape"
author: "Fraser Kerr"
date: "2023-11-28"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
gdp <- read_delim("../In_class_files/oecd-gdp.csv.bz2")
gdp %>%
  head()
```

```{r}
gdpLong <- 
  gdp %>% 
  pivot_longer(!c(country, indicator))
  gdpLong %>%
  head(10)
```

```{r}
gdpLong <- 
  gdp %>% 
  pivot_longer(!c(country, indicator),
               names_to = "year",
               values_to = "gdp")
  gdpLong %>%
  head(10)
```

```{r}
gdpLong <- 
  gdp %>% 
  pivot_longer(!c(country, indicator),
               names_to = "year",
               values_to = "gdp") %>% 
  mutate(year = as.numeric(year))
  gdpLong %>%
  head(10)
```

##Exercise
```{r}
p <- data.frame(pregnant = c("Yes", "No"),
            	male = c(NA, 25),
            	female = c(11, 18))
p
```

```{r}
pl <- p %>%
  pivot_longer(c(male, female),
               names_to = "sex",
               values_to = "count")
pl
```

```{r}
pl %>% 
  pivot_wider(id_cols = pregnant,
              names_from = sex,
              values_from = count)
```

